version: '2'

services:
  web_app:
    image: joomla:3.7-apache
    container_name: ${WEB_APP_CONTAINER_NAME}
    environment:
      - JOOMLA_DB_HOST=${DB_HOST}:${DB_PORT}
      - JOOMLA_DB_USER=${DB_USER}
      - JOOMLA_DB_PASSWORD=${DB_PASS}
      - JOOMLA_DB_NAME=${DB_NAME}
      - HTTP_PROXY=${http_proxy}
      - HTTPS_PROXY=${https_proxy}
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
    ports:
      - ${WEB_APP_PORT}:80
    volumes:
      - ${WEB_APP_DATA_DIR}:/var/www/html
    #network_mode: "host"