FROM php:7.1.5-apache

LABEL maintainer Sergey Kochetkov <legatdestr@gmail.com>
ENV YII2_DEV_WEB_SERVER_VERSION 0.0.1

ENV LIBS_TO_INSTALL \
     libfreetype6-dev \
     libjpeg62-turbo-dev \
     libpng12-dev \
     libmcrypt-dev \
     libpq-dev \
     libicu52 \
     libicu-dev \
     git \
     git-core

RUN apt-get update && apt-get install -y \
  $LIBS_TO_INSTALL --no-install-recommends \
  && docker-php-ext-install -j$(nproc) iconv mcrypt zip intl bcmath json mbstring pdo pdo_pgsql pgsql \
  && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
  && docker-php-ext-install -j$(nproc) gd \
  && rm -r /var/lib/apt/lists/*

RUN pear config-set http_proxy ${http_proxy} && pecl install xdebug-2.5.5

# install composer globally
RUN curl -sS https://getcomposer.org/installer | php -- --version=1.4.2 --install-dir=/usr/local/bin --filename=composer
# install Composer Asset Plugin for Yii2
RUN composer global require --prefer-dist "fxp/composer-asset-plugin:~1.3"


RUN mkdir -p '/var/www/vhosts/app' && \
    mkdir -p '/var/www/libs/app/config' && \
    mkdir -p '/var/www/libs/app/vendor' && \
    mkdir -p '/var/www/vhosts/app/.ht_temp' && \
    mkdir -p '/var/www/vhosts/app/htdocs' && \
    rm -rf /var/www/html

COPY configs/custom.php.ini /usr/local/etc/php/custom.php.ini
COPY configs/sites-enabled/ /etc/apache2/sites-enabled/
COPY composer/auth.json  /root/.composer/auth.json

# enable mod_rewrite
RUN ln -s /etc/apache2/mods-available/rewrite.load /etc/apache2/mods-enabled/rewrite.load

WORKDIR /var/www/vhosts/app

EXPOSE 80

# Run Apache2 service
CMD ["apache2-foreground"]
